#!/usr/bin/env node

// Settings Globals
process.env.GA_PROJECT_PATH = process.cwd();
process.env.GA_SESSION_ID = `SESSION_${(new Date).getTime()}`;

const bootstrap = require("./libraries/bootstrap");

// Sets the version
bootstrap.version("1.1.6");

// Boots the creator
bootstrap.create();

// Boots the runner
bootstrap.runner();

// Adds the arguement / options handler
bootstrap.handler();
